services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        BUILD_MODE: local
        APP_VERSION: lesson-06-local
    env_file:
      - .env.example
    environment:
      APP_ENV: local
      DB_HOST: mysql
      REDIS_HOST: redis
    ports:
      - "8000:8000"
