tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localho.st.crt
        keyFile: /etc/traefik/certs/localho.st.key
  certificates:
    - certFile: /etc/traefik/certs/localho.st.crt
      keyFile: /etc/traefik/certs/localho.st.key
